services:
  app:
    image: "python:3-alpine"
    volumes:
      - ./codebase:/codebase
    command: python /codebase/app.py
    env_file: ./.env
    secrets:
      - TOKEN

secrets:
  TOKEN:
    file: ./TOKEN.txt